services:
  - type: web
    name: polcomply-demo
    env: python
    buildCommand: cd backend && pip install -r requirements.txt && cd ../polcomply && pip install -e .
    startCommand: cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11
    healthCheckPath: /health
    autoDeploy: true
