name: CI

on:
  push:
    branches: [ main, develop, feat/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd polcomply && pip install -e ".[dev]"
    
    - name: Run Ruff
      run: cd polcomply && ruff check . --fix
    
    - name: Run Black
      run: cd polcomply && black . --check
    
    - name: Run Tests
      run: cd polcomply && pytest -q